### ISSUE TITLE
Questions about kube-controller-manager and keepalived cloud provider

### ISSUE THREAD

**Issue by baodongli** [ufcg-lsd/k8s-onpremise-federation#2]
Thanks for the detailed procedure. I was following it to deploy a k8s federation. I met with an issue that I couldn't deploy the hello-world application. 
   - I changed /etc/kubernetes/manifests/kube-controller-manager.yaml to add - --cloud-provider=external. Afterwards, I found that the kube-controller-manager disappeared. Is this a normal behavior?
  - I deployed hello-world, but no pods were launched.
  - I then removed --cloud-provider=external. kube-controller-manager pod came back, and the hello-world got deployed
  - However, keepalived didn't work. The keepalived-vip pod didn't have the correct configuration in /etc/keepalived/keepalived.conf since it was always empty.
Your help is hightly appreciated.

**Comment by arthur0** [comment]
What is your Kubernetes version? 

After you edit the kube-controller-manager manifest, the pod should be restarted, not disappear.
If your kube-controller-manager is not healthy, you can't create any kubernetes resource.

The keepalived sometimes is broken, you should check it and if it no ready. Simply delete the pods and they should be created again.

You can do the keepalived [step](https://github.com/ufcg-lsd/k8s-onpremise-federation#deploy_keepalived)  before all others and create the hello-world app without federation. Can you try this? If it not possible, paste the logs here (of keepalived and kube-controller-manager).

You can find the official docs for keepalived [here](https://github.com/munnerz/keepalived-cloud-provider) too.

**Comment by baodongli** [comment]
Thanks for your reply. I originally used k8s 7.5, then switched to 7.3 with no avail. Yeah, I realized that kube-controller-manager must be healthy in order to create any resource. It seems that I have to make the cloud_provider=external config in the --config kubeadm.conf (in the kubeadm init codlin) for kube-controller-manager to stay running. But keepalived still didnt' work. keepalived.conf always had empty config.

**Comment by baodongli** [comment]
It appears that the problem is in this file:k8s-onpremise-federation/keepalived-vip/daemonset.yaml. keepalived-vip and the configmap it uses is deployed in the namespace kube-system, but the flag services-configmap is referring to the configmap cloud-provider/vip-configmap that is in the namespace cloud-provider, which doesn't exist. Hope that this makes sense.
